import { useMemo } from "react";
import type { ComponentKind, SymbolStyle } from "@/lib/circuit";
import { PALETTE_ORDER, SYMBOLS, symbolPreviewSVG } from "@/lib/circuit-symbols";

/* Component palette: a grid of buttons whose previews are generated by the SAME draw
   code as the canvas (SvgPen), so they always match the active symbol style. */
export function Palette({
  style,
  onAdd,
}: {
  style: SymbolStyle;
  onAdd: (kind: ComponentKind) => void;
}) {
  const previews = useMemo(
    () =>
      PALETTE_ORDER.map((kind) => ({
        kind,
        name: SYMBOLS[kind].name,
        svg: symbolPreviewSVG(kind, style),
      })),
    [style],
  );
  return (
    <div className="grid grid-cols-3 gap-1.5">
      {previews.map(({ kind, name, svg }) => (
        <button
          key={kind}
          type="button"
          title={`Add ${name.toLowerCase()}`}
          onClick={() => onAdd(kind)}
          className="group flex flex-col items-center gap-1 rounded-lg border border-input bg-card px-1 pb-1.5 pt-2 transition-colors hover:border-primary hover:bg-accent"
        >
          {/* previews are self-generated SVG strings, not user input */}
          <span className="h-9 w-full" dangerouslySetInnerHTML={{ __html: svg }} />
          <span className="text-[10px] font-medium leading-none text-muted-foreground group-hover:text-foreground">
            {name}
          </span>
        </button>
      ))}
    </div>
  );
}
