/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CircuitRouteImport } from './routes/circuit'
import { Route as IndexRouteImport } from './routes/index'

const CircuitRoute = CircuitRouteImport.update({
  id: '/circuit',
  path: '/circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/circuit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/circuit'
  id: '__root__' | '/' | '/circuit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitRoute: typeof CircuitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/circuit': {
      id: '/circuit'
      path: '/circuit'
      fullPath: '/circuit'
      preLoaderRoute: typeof CircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitRoute: CircuitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
